apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: consul
resources:
  - database.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: consul
    newName: rg.fr-par.scw.cloud/djnd/consul
    newTag: 'latest'
  # - name: consul-assets
  #   newName: rg.fr-par.scw.cloud/djnd/consul-assets
  #   newTag: '0eeb48a814a0791eb79d2aeac2413f2d59014f1f'
