apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: consul
resources:
  - database.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: consul
    newName: rg.fr-par.scw.cloud/djnd/consul
    newTag: '22325268b295146037ba80835a6b718ab30715f1'
  # - name: consul-assets
  #   newName: rg.fr-par.scw.cloud/djnd/consul-assets
  #   newTag: '22325268b295146037ba80835a6b718ab30715f1'
