language: ruby
addons:
  postgresql: "9.4"
rvm:
 - "2.3.2"
cache: bundler
before_script:
  - "for i in config/*.example; do cp \"$i\" \"${i/.example}\"; done"
  - bundle exec rake db:setup
script: bundle exec rake
