language: ruby
addons:
  postgresql: "9.4"
  chrome: stable
cache: bundler
bundler_args: --without development
before_script:
- for i in config/*.example; do cp "$i" "${i/.example}"; done
- bundle exec rake db:setup
script:
- "bundle exec rake assets:precompile RAILS_ENV=test > /dev/null 2>&1"
- "bin/knapsack_pro_rspec"
env:
  global:
  - KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
  - KNAPSACK_PRO_LOG_LEVEL=info
  - KNAPSACK_PRO_CI_NODE_TOTAL=5
  matrix:
  - KNAPSACK_PRO_CI_NODE_INDEX=0
  - KNAPSACK_PRO_CI_NODE_INDEX=1
  - KNAPSACK_PRO_CI_NODE_INDEX=2
  - KNAPSACK_PRO_CI_NODE_INDEX=3
  - KNAPSACK_PRO_CI_NODE_INDEX=4
notifications:
  slack:
    secure: 18E9SU0SR/9knRvCMYwVqFCqVTBT6qJtZQ/gadpheqUPPlcLoQfnlIzJkLIYqkE0sn1nkBE5Bt2I90FU53p0NkrTEmSGlQXcN1vEXM8EXMaoVf3NBsIJeleMwt9VTojzo81EgIi6x7q3fDiFORJ4rqOGd9XkeLn5yrAtIkdaenVs0bhS5s24FP76hKqO37IFLG2v3EEqxg5k31oW6yhyP35Mxns+AGbfaZbxEy4XbCoU65KFuYhBsVZ/y1evOl/wcre2fCAoT2uKeqUWGEcDzH7oSCz7vfk7iO9BZnO++v7oj8mr/nrZL1KMFt77eqtdT51XQoJcchgJC/R9km5hRGkQqFCHhqPcBxo5c3p+jauL0kLaqTggeLDv2FQ2huJ8FSJ4ADac+n3g7wT7BX7HJlCvK0nbooY1JtBlk7+6/pw6ksSFIOo0FHg5gXN9IlG1tQQuENzzsXULNc6s4nPeT+n78uOp1b0N/Gn06moEBaKgXqqx1yV1XeJ02X8n3uDZxPuX3n2bJ4DMIrBjeWApxHAgyOraOzQHNQgJoj4tHlWutF33ApV2tcIMefIzvjM4tIYwIkpfGgohGaTf8eU5X9pqiMgwlDpJHVBsSvpk/Z/Nj7evYznjBiDYqOcXoztsqHrS0C91MaT+eExDfd9HDmThsE07RT7zcP9aElFZA/k=
    on_failure: always
    on_success: change
