language: ruby
addons:
  postgresql: '9.4'
  chrome: stable
rvm:
  - 2.3.2
cache: bundler
bundler_args: --without development
before_script:
  - wget -N https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - for i in config/*.example; do cp "$i" "${i/.example}"; done
  - bundle exec rake db:setup
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - "bundle exec rake assets:precompile RAILS_ENV=test > /dev/null 2>&1"
  - "bin/knapsack_pro_rspec"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
env:
  global:
  - KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
  - KNAPSACK_PRO_LOG_LEVEL=info
  - KNAPSACK_PRO_CI_NODE_TOTAL=2
  matrix:
  - KNAPSACK_PRO_CI_NODE_INDEX=0
  - KNAPSACK_PRO_CI_NODE_INDEX=1
notifications:
  email:
    recipients:
      - emilien@happy-dev.fr
      - claire.zuliani@happy-dev.fr
    on_failure: always
    on_success: change
