language: ruby
addons:
  postgresql: "9.4"
rvm:
 - "2.3.2"
cache: bundler
bundler_args: --without development
before_script:
  - "for i in config/*.example; do cp \"$i\" \"${i/.example}\"; done"
  - bundle exec rake db:setup
script:
  - "bundle exec rake assets:precompile RAILS_ENV=test"
  - "bin/knapsack_pro_rspec"
env:
  global:
    - CI_NODE_TOTAL=2
    - KNAPSACK_PRO_CI_NODE_TOTAL=2
    - secure: KTKnEVkT28dxldpq7CBCF2Vd0AiQFDgwsVMhq82vw+CTJibQKnOSts+x7azcXWfCnTTklybmocUowb/NWV4vpo3tyAZrZfnO8nzK/Ztu/Ki2x2ranLRxSXvuNkyF5z1E3xeGL/XOcKN8b/CAR1ZPE2OsEko8S/qSY/Y4dPjMH+bFEpEqBvkTpn5Ze4uW7IsmGsEUsElk9fDZPuDElNiVhMAYL8/cpEI/EucSqYrGqu0ulHHeUICG1bkoCQziCrvU+LdFQRh5OXyhSO5/OmYJwjcNuI/jS97VK50GFyxlssTJHChiTSWhT/8afM5pM/uu/cDJKDL0zDmAce+Fy/xSjFCby4jN7vscNpbZ6lGyIW2uqBFX/Ri4jZVyzu9qgwEeKhsrsfsfSMEjx9JMvUiuyAn15SFrN8+bzztU2GVbYd189L8hEa/8T899zE8z80oyRs8Keq+qVgk4MwfvAz3dHh7Z2/OKS2d6Vru0nZLGT11ucm4X1JnuRAe4pDAsJ5kvXKRr3qeF2qRoVOtrEqJHjY30Ipx6mGJfbMmxEQQgWGnHHS8ogRiXG4vIXvyqzlnsTJTUxu7ASuBWxVBAgZalxD1kcyF2ZZ3jCzXSJphPQGiZNDzHgZeR7AwK61c9uwqEB/XoswoXZO5RlMiIVZIGp/tZDkDcHlrPmFdMgxboP8Y=
    - secure: G/lHi3kzYucmNDGTvQmzUM4OPiokHLX8lOSFoZXGIq5bCG77dT5bYi6WRc7+wimozrdQxAGEgX++c8yxJcxNU7JzhpRwNukQ7ic0pwSwHDdRjFwSLznlJOmoSxiBGjy+C/O3XRHN/8SaU7trcUp7nGQiIZIp4LyHFw6REA0o+ZrDoQ/EjmnraF0udJcR/t8Y3MvxlWjausUxjbciaf8xQi9HlBUWnJpNg5HeUAG2aSejlya1/PQhBRN8KcqCsKphK9D39ulOQOmWPdsE4RkG3e3l3670e5Nw4s4coGzOxfVPo6EK6iJ/XREhGbJ6F/YpfseybJICA/m0KUAIGhmvcUuEOE/fM0hUMjbueA1lZDD7pstnvu+EUH2fuIBOAltg9KaSgrIy5Hpbf7j0gQobDWRvl5VA/OIBMT3MOZq/FXeugqM3MM6Ub4djdvpVt2DzY9ckPPUBHM4uPcDhuk0rQFdpC6DeKYyyGizELCpll892I6vmXece4uTcCtPLVGdNmMNfTVDWHKWX0lAfarVVEmvzmhj04YJ62bPsuWtOBJNRzZ9UA3pRAj/XCXAP2BGAC0nBfIg2S7NjTaF7WAZZ6FPncB8ubMhMd2AiAQTIZq8PF+fLRN+aPWDqpTDieK1wwzN2klZBJ5STexZ3XwdqOuVp330NWbfiGGNW3DiBcC0=
  matrix:
    - KNAPSACK_PRO_CI_NODE_INDEX=0
    - KNAPSACK_PRO_CI_NODE_INDEX=1
