defaults: &defaults
  # Org name of the website.
  org_name: "Decidim Barcelona"

  # City or organization.
  place_name: "Barcelona"

  # Names for the moderation console, as a hint for moderators
  # to know better how to assign users with official positions
  official_level_1_name: "Empleados públicos"
  official_level_2_name: "Organización Municipal"
  official_level_3_name: "Directores generales"
  official_level_4_name: "Concejales"
  official_level_5_name: "Alcaldesa"

  # Max percentage of allowed anonymous votes on a debate
  max_ratio_anon_votes_on_debates: 50

  # Max votes where a debate is still editable
  max_votes_for_debate_edit: 1000

  # Max votes where a proposal is still editable
  max_votes_for_proposal_edit: 1000

  # Prefix for the Proposal codes
  proposal_code_prefix: 'MAD'

  # Number of votes needed for proposal success
  votes_for_proposal_success: 53726

  # Users with this email domain will automatically be marked as level 1 officials
  # Emails under the domain's subdomains will also be included
  email_domain_for_officials: ''

  twitter_handle: "decidimbcn"
  facebook_handle: ~
  youtube_handle: "decidimbcn"
  blog_url: ~

  url: "https://decidimbcn.herokuapp.com"

  # Users with this email domain will automatically be marked as level 1 officials
  # Emails under the domain's subdomains will also be included
  email_domain_for_officials: ''

  # Code to be included at the top (header) of every page (useful for tracking)
  per_page_code: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
