default: &default
  secret_key_base: "<%= ENV['SECRET_KEY_BASE'] %>"

  census_api_end_point: "<%= ENV['CENSUS_API_END_POINT'] %>"
  census_api_institution_code: "<%= ENV['CENSUS_API_INSTITUTION_CODE'] %>"
  census_api_portal_name: "<%= ENV['CENSUS_API_PORTAL_NAME'] %>"
  census_api_user_code: "<%= ENV['CENSUS_API_USER_CODE'] %>"

  sms_end_point:  "<%= ENV['SMS_END_POINT'] %>"
  sms_username: "<%= ENV['SMS_USERNAME'] %>"
  sms_password: "<%= ENV['SMS_PASSWORD'] %>"

  http_basic_username: "<%= ENV['HTTP_BASIC_USERNAME'] %>"
  http_basic_password: "<%= ENV['HTTP_BASIC_PASSWORD'] %>"

  twitter_key: "<%= ENV['TWITTER_KEY'] %>"
  twitter_secret: "<%= ENV['TWITTER_SECRET'] %>"
  facebook_key: "<%= ENV['FACEBOOK_KEY'] %>"
  facebook_secret: "<%= ENV['FACEBOOK_SECRET'] %>"
  google_oauth2_key: "<%= ENV['GOOGLE_OAUTH2_KEY'] %>"
  google_oauth2_secret: "<%= ENV['GOOGLE_OAUTH2_SECRET'] %>"

  rollbar_access_token: "<%= ENV['ROLLBAR_ACCESS_TOKEN'] %>"
  server_name: "<%= ENV['SERVER_NAME'] %>"
  email: "<%= ENV['EMAIL'] || 'info@decidim.barcelona' %>"

  google_maps_api_key: "<%= ENV['GOOGLE_MAPS_API_KEY'] %>"

  translate_username: "<%= ENV['TRANSLATE_USERNAME'] %>"
  translate_password: "<%= ENV['TRANSLATE_PASSWORD'] %>"

  census_url: "<%= ENV['CENSUS_URL'] %>"

development:
  <<: *default
  secret_key_base: "56792feef405a59b18ea7db57b4777e855103882b926413d4afdfb8c0ea8aa86ea6649da4e729c5f5ae324c0ab9338f789174cf48c544173bc18fdc3b14262e4"
  email: email@example.com

test:
  <<: *default
  secret_key_base: "56792feef405a59b18ea7db57b4777e855103882b926413d4afdfb8c0ea8aa86ea6649da4e729c5f5ae324c0ab9338f789174cf48c544173bc18fdc3b14262e4"
  email: email@example.com
  census_url: "https://fake.url"

production:
  <<: *default
