local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

s3:
  service: S3
  access_key_id: <%= ENV['CONSUL_AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['CONSUL_AWS_SECRET_ACCESS_KEY'] %>
  region: fr-par
  bucket: <%= ENV['CONSUL_AWS_S3_BUCKET_NAME'] %>
  endpoint: https://s3.fr-par.scw.cloud

# Remember not to checkin your GCS keyfile to a repository
# gcs:
#   service: GCS
#   project: <%= Rails.application.secrets.dig(:gcs, :project) %>
#   credentials: <%= Rails.root.join(Rails.application.secrets.dig(:gcs, :credentials).to_s) %>
#   bucket: <%= Rails.application.secrets.dig(:gcs, :bucket) %>

# azure:
#   service: AzureStorage
#   storage_account_name: <%= Rails.application.secrets.dig(:azure, :storage_account_name) %>
#   storage_access_key: <%= Rails.application.secrets.dig(:azure, :storage_access_key) %>
#   container: <%= Rails.application.secrets.dig(:azure, :container) %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ s3, gcs, azure ]
