name: Kanban management
on:
  pull_request_target:
    types: [opened, reopened]
permissions:
  contents: read
env:
  MY_GITHUB_TOKEN: ${{ secrets.KANBAN_TOKEN }}

jobs:
  assign_one_project:
    permissions:
      repository-projects: write  # for srggrs/assign-one-project-github-action to assign issues and PRs to repo project
    name: Add new pull requests to the kanban
    if: github.repository_owner == 'consul'
    runs-on: ubuntu-latest
    steps:
    - name: Assign new pull requests to the reviewing column
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.pull_request.draft == false
      with:
        project: "https://github.com/orgs/consul/projects/1"
        column_name: "Reviewing"

    - name: Assign new draft pull requests to the doing column
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.pull_request.draft == true
      with:
        project: "https://github.com/orgs/consul/projects/1"
        column_name: "Doing"
