on:
  push:
    branches:
      - djnd-consul

jobs:
  pull-requests:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2

      -
        name: pull-request-maribor
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "maribor-k8s"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Pulling ${{ github.ref }} into maribor-k8s"

      -
        name: pull-request-medvode
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "medvode-k8s"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Pulling ${{ github.ref }} into medvode-k8s"

      -
        name: pull-request-koper
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "koper-k8s"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Pulling ${{ github.ref }} into koper-k8s"

      -
        name: pull-request-hrpelje-kozina
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "hrpelje-kozina-k8s"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Pulling ${{ github.ref }} into hrpelje-kozina-k8s"

      -
        name: pull-request-staging
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "staging-k8s"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Pulling ${{ github.ref }} into staging-k8s"
