name: Publish Docker image
on:
  push:
    branches:
      - 'djnd-consul-turned-off' # temporarily turn off the workflow
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Scaleway
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/djnd
          username: nologin
          password: ${{ secrets.SCW_SECRET_TOKEN }}
      -
        name: Build and push consul
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            rg.fr-par.scw.cloud/djnd/consul:${{ github.sha }}
            rg.fr-par.scw.cloud/djnd/consul:staging
      # -
      #   name: Build and push assets
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./nginx.Dockerfile
      #     push: true
      #     tags: |
      #       rg.fr-par.scw.cloud/djnd/consul-assets:${{ github.sha }}
      #       rg.fr-par.scw.cloud/djnd/consul-assets:staging
      -
        name: Update image versions in kustomize/kustomization.yaml
        run: |
          sed -i "s/newTag: .*\+/newTag\: '${{ github.sha }}'/" kustomize/kustomization.yaml
      -
        name: Commit and push new image versions
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: '.'
          author_name: GitHub action

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Update image versions in kustomize/kustomization.yaml'

          # The flag used on the pull strategy. Use NO-PULL to avoid the action pulling at all.
          # Default: '--no-rebase'
          # 'NO-PULL or --no-rebase or --no-ff or --rebase'
          pull_strategy: 'NO-PULL'
